### ISSUE TITLE
Opcion para cambiar idiomas

### ISSUE THREAD

**Issue by merRen22** [rpgdevs/landing#2]
De momento solo se dará soporta al ingles y al español

Aqui las traducciones:
[RPG WEB.docx](https://github.com/user-attachments/files/15845140/RPG.WEB.docx)

Los texto en amarillo son correcciones textos. Lo de rojo es texto que solo debe salir en un idioma

**Comment by merRen22** [comment]
@gabosh140 estuvimos viendo con Marco seria buena idea tener un boton floatante para el numero de telefono o lo mantenemos en el footer como esta hoy?

**Comment by gabosh140** [comment]
@merRen22 correcto procedan con el boton flotante

**Comment by merRen22** [comment]
Dale lo haremos como una segunda parte de esta tarea. Despues de hacer el formulario
